### ISSUE TITLE
Update Student Posters

### ISSUE THREAD

**Issue by StoneyJackson** [CCSCNE/ccscne.org#7]
8. Student Posters
Sandeep Mitra has suggested some changes to the language on our web page that we use
to describe student posters. The following are Sandeep’s specific recommendations.
“One, at the Undergraduate Research page, the sentence “No other formats (such as PDF)
will be accepted” should be bolded. But perhaps more importantly, in the actual
submission form, the option to choose PDF as the submission format should be
eliminated. I realize that those forms date from a number of years ago, but I hope it is
possible to edit the code. This was the primary cause of confusion among many
submitters this year, according to feedback received.
Two, in the “Submit” section, we have the sentence “A confirmation will be emailed to
you”. This should be changed to “A confirmation email with the submission number
clearly indicated will be sent to you”. Following this sentence, we should have the
following sentence(s) in bold: “Please note that if you did not receive such a confirmation
email for each poster submitted, your submission has not been received. Any
correspondence should quote the submission number. It will not be possible for us to
entertain inquiries about your poster without reference to the submission number”.
Third, in the “Submit” section, we should have another paragraph that says: “Early
submissions of poster abstracts are STRONGLY encouraged. A submission received a
week or so before the deadline gives the committee a chance to preview your submission
and contact you regarding any issues such as formatting. It is usually not possible for us
to consider incorrectly submitted abstracts beyond the stipulated deadline”.
In the section, “How should undergraduate posters be displayed at the conference?” the
sentence “At least one of the authors must register for the conference by the early
registration date and be there to present the poster during the Undergraduate Posters
session” should be bolded. The following sentence should be changed to “A poster
abstract will be removed from the conference documentation if an author does not
register. Also, a poster will be disqualified from the competition if at least one presenter
is not present.” ”

**Comment by kwurst** [comment]
Moved to Trello board
